version: "3.8"
services:
  my-app:
    build:
        context: .
        target: ${MY_ENV}
    image: my-node-app:${MY_ENV}
    ports:
      - "8501:8000"
    volumes:
      - ./src:/app/src
    environment:
      PORT: ${MY_PORT}