name: "01-EKS"
on:
  workflow_dispatch:

jobs:
  Plan:
    uses: Vidushimodi/Khaanvani-Org/prod/.github/workflows/deploy.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: VidushiModi/Khaanvani-Orgprod/.github/workflows/deploy.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
